
//test server endpoint ok 
GET http://localhost:5000 

###
POST http://localhost:5000/api/users
content-type: application/json


{
    "name":"nico",
    "email":"nico@free.fr",
    "password":"test123"
}

###
POST http://localhost:5000/api/auth
content-type: application/json

{
    "email":"nico@free.fr",
    "password":"test123"
}

###
GET http://localhost:5000/api/auth
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWY4NTZkYzc1YTY3MDk0OWIxNDUwYTJiIn0sImlhdCI6MTYwMjU4MzI0NSwiZXhwIjoxNjAyNjE5MjQ1fQ.OT85xA26qtbblah6YJSbhmU5IeZoUqwfY21IwU8gh68





###
GET http://localhost:5000/api/contacts

###
POST http://localhost:5000/api/contacts

content-type: application/json
{}

###
PUT  http://localhost:5000/api/contacts/id

content-type: application/json
{}

###
DELETE   http://localhost:5000/api/contacts/id

content-type: application/json
{}