
//test server endpoint ok 
GET http://localhost:5000 

###
POST http://localhost:5000/api/users
content-type: application/json


{
    "name":"nico",
    "email":"test123@free.fr",
    "password":"test123"
}

###
POST http://localhost:5000/api/auth
content-type: application/json

{}

###
GET http://localhost:5000/api/contacts

###
POST http://localhost:5000/api/contacts

content-type: application/json
{}

###
PUT  http://localhost:5000/api/contacts/id

content-type: application/json
{}

###
DELETE   http://localhost:5000/api/contacts/id

content-type: application/json
{}